# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "ahci" "xhci_pci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = ["dm-snapshot" "dm-cache"];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  #crypttab for lvm drives
  environment.etc.crypttab.text = ''
    home_hdd UUID="5bd75570-c441-4509-b21c-144cd13838b5" /nix/persist/keyfiles/home_hdd
    home_ssd UUID="3d67fb6e-d7a8-41a6-9e7b-6fbbe5309f6b" /nix/persist/keyfiles/home_ssd
  '';

  fileSystems."/" = {
    device = "tmfs";
    fsType = "tmpfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E939-E650";
    fsType = "vfat";
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/8455ca75-43e5-4a7d-9d0f-96950408f262";
    fsType = "f2fs";
  };

  boot.initrd.luks.devices."root" = {
    device = "/dev/disk/by-uuid/a4cb3149-6939-4416-8cdd-0d9bf3a8306f";
    allowDiscards = true;
  };

  fileSystems."/nix/persist/home" = {
    device = "/dev/disk/by-uuid/047830f0-a9d4-4c1f-b1c7-7af9a2b7337e";
    fsType = "ext4";
  };

  #nfs
  fileSystems."/mnt/nas" = {
    device = "192.168.0.238:/mnt/nas/nas/mainpc";
    fsType = "nfs";
    options = ["x-systemd.automount" "noauto"];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp39s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp49s0f3u3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
